[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = []

[[redirects]]
  from = "/api/trimet/*"
  to = "/.netlify/functions/trimet/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/streetcar"
  to = "/.netlify/functions/streetcar"
  status = 200
  force = true

[[redirects]]
  from = "/api/streetcar/*"
  to = "/.netlify/functions/streetcar/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
